name: eclipsenets
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - heyoka.py
  - scipy
  - matplotlib
  - tqdm
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - pyvista
  - shapely
  - pip
  - pip:
      - tetgen