name: eclipsenets
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - shapely>=2.0
  - matplotlib
  - tqdm
  - heyoka.py>=7.0
  - pytorch
  - jupyterlab
  - nbconvert
  - pytest
  - git-lfs
  - pip
